apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: demo
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8889
    name: demo8889
  selector:
    app: demo-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-2048
  namespace: demo
  labels:
    app: demo-2048
    name: demo-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-2048
      name: demo-2048
  template:
    metadata:
      labels:
        app: demo-2048
        name: demo-2048
    spec:
      containers:
        - name: demo-2048
          image: >-
            10.24.2.36/demo/demo-2048:{{build_tag}}
          ports:
            - containerPort: 8080
              name: demo8889
              protocol: TCP
          resources:
            limits:
              cpu: 128m
              memory: 256Mi
            requests:
              cpu: 128m
              memory: 128Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor
