apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-2048
  labels:
    app: demo-2048
    name: demo-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-2048
      name: demo-2048
  template:
    metadata:
      labels:
        app: demo-2048
        name: demo-2048
    spec:
      containers:
        - name: demo-2048
          image: 10.24.2.3/demo/demo-2048:v1.0
          ports:
            - containerPort: 8080
              name: demo8889
              protocol: TCP



