image: docker:stable
stages:
  - package
  - docker_build
  - deploy_k8s_demo
  - deploy_k8s_server
  
  
variables:
  KUBECONFIG: /etc/deploy/config
#  MAVEN_OPTS: "-Dmaven.repo.local=/opt/cache/.m2/repository"

mvn_build_job:
  image: 10.24.2.3/demo/maven:3.6-jdk-8
  stage: package
  only:
    - drone
  tags:
    - k8s-runner
  script:
    - mvn clean install -DskipTests=true
    - cd target && jar -xf 2048.war
    - ls -l
    - pwd


docker_build_job:
  image: docker:latest
  stage: docker_build
  tags:
    - k8s-runner
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD 10.24.2.3
    - pwd
    - cd Dockerfiles
    - docker build -t 10.24.2.3/demo/demo-2048:$CI_PIPELINE_ID .
    - docker push 10.24.2.3/demo/demo-2048:$CI_PIPELINE_ID

deploy_k8s_demo:
  image: kubectl:1.16.6
  stage: deploy_k8s_demo
  tags:
    - k8s-runner
  script:
    - mkdir -p /etc/deploy
    - echo $kube_config |base64 -d > $KUBECONFIG
    - kubectl apply -f template/demo-2048.yaml

deploy_k8s_server:
  image: kubectl:1.16.6
  stage: deploy_k8s_server
  tags:
    - k8s-runner
  script:
    - mkdir -p /etc/deploy
    - echo $kube_config |base64 -d > $KUBECONFIG
    - kubectl apply -f template/service.yaml


